# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Junit2html < Formula
  desc "Crazy fast local dev loop."
  homepage "https://github.com/kitproj/junit2html"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kitproj/junit2html/releases/download/v0.0.5/junit2html_0.0.5_Darwin_arm64.tar.gz"
      sha256 "10d33fa94fcffa6d08244830092068874cc5702aa085ffd65a04fe7ca0aa786c"

      def install
        bin.install "junit2html"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kitproj/junit2html/releases/download/v0.0.5/junit2html_0.0.5_Darwin_x86_64.tar.gz"
      sha256 "6d393f9d16a4e35e2a0398fb06ebaaa261bba0db592cd073a78e2b9b6da448e9"

      def install
        bin.install "junit2html"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kitproj/junit2html/releases/download/v0.0.5/junit2html_0.0.5_Linux_arm64.tar.gz"
      sha256 "eaa26ce5ed062ecafc53943f2a778fee2b34fd493b72a0f01d5d11e4b014b128"

      def install
        bin.install "junit2html"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kitproj/junit2html/releases/download/v0.0.5/junit2html_0.0.5_Linux_x86_64.tar.gz"
      sha256 "4e3a2fdecb7213d92410c516720de9e5192f30b32cd22e9a05b8b1d1d9c5c74b"

      def install
        bin.install "junit2html"
      end
    end
  end
end
